DROP TABLE IF EXISTS cms_nppes CASCADE;
CREATE TABLE "cms_nppes" (
"npi" varchar(10) NOT NULL,
"entity_type_code" varchar(1),
"npi_deactivation_reason_code" varchar(2),
"npi_deactivation_date" date,
"npi_reactivation_date" date,
"replacemant_npi" varchar(10),
"employer_identification_number" varchar(10),
"is_sole_proprietor" bool,
"is_org_subpart" bool,
"parent_org_lnb" varchar(100),
"parent_org_tin" varchar(9),
"provider_org_name" varchar(100),
"provider_other_organization_name" varchar(100),
"provider_other_organization_name_type_code" varchar(1),
"provider_last_name" varchar(50),
"provider_first_name" varchar(50),
"provider_middle_name" varchar(50),
"provider_name_prefix" varchar(10),
"provider_name_suffix" varchar(10),
"provider_credential" varchar(50),
"provider_other_last_name" varchar(50),
"provider_other_first_name" varchar(50),
"provider_other_middle_name" varchar(50),
"provider_other_name_prefix" varchar(10),
"provider_other_name_suffix" varchar(10),
"provider_other_credential" varchar(50),
"provider_other_name_type_code" varchar(1),
"providre_gender_code" varchar(1),
"provider_enumeration_date" date,
"last_update_date" date,
"authorizing_official_last_name" varchar(50),
"authorizing_official_first_name" varchar(50),
"authorizing_official_middle_name" varchar(50),
"authorizing_official_name_prefix" varchar(10),
"authorizing_official_name_suffix" varchar(10),
"authorizing_official_title_or_position" varchar(50),
"authorizing_official_telephone_number" varchar(20),
"authorizing_official_credential" varchar(20),
PRIMARY KEY ("npi") ,
CONSTRAINT "fk_cms_nppes_cms_nppes_provider_licenses_1" FOREIGN KEY ("npi") REFERENCES "cms_nppes_provider_licenses" ("npi"),
CONSTRAINT "fk_cms_nppes_cms_nppes_provider_address_1" FOREIGN KEY ("npi") REFERENCES "cms_nppes_provider_address" ("npi"),
CONSTRAINT "fk_cms_nppes_cms_nppes_provider_taxonomy_group_1" FOREIGN KEY ("npi") REFERENCES "cms_nppes_provider_taxonomy_group" ("npi"),
UNIQUE(provider_first_name)
)
;



INSERT INTO cms_nppes
SELECT
	npi,
	entity_type_cd,
	npi_deactivation_reason_cd,
	case when npi_deactivation_date = '' then null else cast(npi_deactivation_date as date) end,
	case when npi_reactivation_date = '' then null else cast(npi_reactivation_date as date) end,
	replacement_npi,
	employer_id_num_ein,
	case when is_sole_proprietor = '' then null when is_sole_proprietor = 'X' then is_sole_proprietor = 'Y' else cast(is_sole_proprietor as boolean) end,
	case when is_org_subpart = '' then null else cast(is_org_subpart as boolean) end,
	parent_org_lbn,
	parent_org_tin,
	prov_org_name_legal_business_name,
	prov_other_org_name,
	prov_other_org_name_type_cd,
	prov_last_name_legal_name,
	npi,
	prov_middle_name,
	prov_name_prefix_text,
	prov_name_suffix_text,
	prov_cred_text,
	prov_other_last_name,
	prov_other_first_name,
	prov_other_middle_name,
	prov_other_name_prefix_text,
	prov_other_name_suffix_text,
	prov_other_cred_text,
	prov_other_last_name_type_cd,
	prov_gender_cd,
	case when prov_enumeration_date = '' then null else cast(prov_enumeration_date as date) end,
	case when last_update_date = '' then null else cast(last_update_date as date) end,
	auth_offcl_last_name,
	auth_offcl_first_name,
	auth_offcl_middle_name,
	auth_offcl_name_prefix_text,
	auth_offcl_name_suffix_text,
	auth_offcl_title_or_position,
	auth_offcl_phone_num,
	auth_offcl_cred_text
FROM
	ref_cms_nppes;
